"""use new models Page and User

Revision ID: 1dffbaca8b71
Revises: c53b85a26bb2
Create Date: 2020-07-26 15:14:45.439124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dffbaca8b71'
down_revision = 'c53b85a26bb2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
