"""use new model User

Revision ID: 850fe50d213a
Revises: 1dffbaca8b71
Create Date: 2020-07-26 20:29:06.803176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850fe50d213a'
down_revision = '1dffbaca8b71'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
