"""use new model User

Revision ID: 1f09c043e83d
Revises: 850fe50d213a
Create Date: 2020-07-26 22:00:51.706450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f09c043e83d'
down_revision = '850fe50d213a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
